export const STATE_ADD_MODAL = "STATE_ADD_MODAL";
export const STATE_MODAL_CONFIRM = "STATE_MODAL_CONFIRM";
export const STATE_FORM_ERROR = "STATE_FORM_ERROR";
export const STATE_ADD_EMPLOYEE  = "STATE_ADD_EMPLOYEE";
export const STATE_DELETE_EMPLOYEE  = "STATE_DELETE_EMPLOYEE";
export const STATE_UPDATE_EMPLOYEE  = "STATE_UPDATE_EMPLOYEE";
export const CREATE_MODE_FORM  = "CREATE_MODE_FORM";
export const UPDATE_MODE_FORM  = "UPDATE_MODE_FORM";

export const VERIFY_UNIQUE_INSS_VALUE = "VERIFY_UNIQUE_INSS_VALUE";
export const VERIFY_UNIQUE_EMAIL_VALUE = "VERIFY_UNIQUE_EMAIL_VALUE";
export const VERIFY_UNIQUE_ID_VALUE = "VERIFY_UNIQUE_ID_VALUE";

export const EMPLOYEES_LIST_STORAGE = "state_employees_list";

export const IDENTIFICATION_LENGTH = 16;
export const INSS_LENGTH = 9;

export const STATUS_ERROR = true;
export const STATUS_SUCCESS = false;